[package]
name = "basic_auth"
version = "0.1.0"
edition = "2021"

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
reqwest = { version = "0.10", features = ["blocking", "json"] }
anyhow = "1.0"
tokio = { version = "0.2.3", features = ["full"] }
